name: HenDeveloper MacOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  macos-with-tailscale:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Random Admin Password
        id: password
        run: echo "password=$(LC_CTYPE=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 4)" >> $GITHUB_ENV

      - name: Create Admin Account
        run: |
          sudo sysadminctl -addUser HenDeveloper -password $password
          sudo dscl . -append /Groups/admin GroupMembership HenDeveloper

      - name: Install Tailscale
        run: |
          brew install tailscale

      - name: Start Tailscale Daemon
        run: |
          sudo tailscaled &

      - name: Verify Tailscale Daemon
        run: |
          if ! pgrep tailscaled > /dev/null; then
            echo "Tailscale daemon failed to start!"
            exit 1
          fi

      - name: Authenticate Tailscale
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          sudo tailscale up --authkey=$TAILSCALE_AUTHKEY

      - name: Get Tailscale IP
        id: tailscale_ip
        run: |
          TAILSCALE_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV

      - name: Display Login Information
        run: |
          echo "========================================="
          echo "Tailscale IP: $TAILSCALE_IP"
          echo "Username: HenDeveloper"
          echo "Password: $password"
          echo "========================================="

      - name: Continuous Status Logging
        run: |
          while true; do
            echo "$(date): Hen MacOS Status - MacOS Active"
            sleep 10
          done
